export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
export const UPDATE_FORM_STATE = 'UPDATE_FORM_STATE';
export const SET_FORM_DATA = 'SET_FORM_DATA';

export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const RESET_FETCH_STATUS = 'RESET_FETCH_STATUS';
